language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
before_script:
- npm install --global @dhis2/deploy-build
script:
- npm run build
deploy:
- provider: script
  script: deploy-build
  skip_cleanup: true
  on:
    all_branches: true
- provider: script
  script: publish-build
  skip_cleanup: true
  on:
    tags: true
env:
  global:
    secure: SRz1n/FkP8HepIhNZn4OV1smQpyrUIcgQNyDh9uoNP+iMfrT10s+Eg0lKOLn1zUMFvdpdNUFDJuD7CGj3xxwTG8uuTggtRssYqHQrqMPTb/vvvgR/BCewGwp30Ld0ZpCKwkGaHGeefFI9MkQWUHl1sacu2a/+Sh/R/oC1YNIHqmO8aWIGJTuIzG+baWGGIw3al/haMWddPVJm1yppUrXn3J/mfkRIqfj7H7SHmI13usOBSF6XVum6BtHKeejAHeReEGN8hdB2ZUyTqW6sUTfxVrt1WbVm7TnYHtk9CC0FgjrMes3wg366dewQzfmY5af6HWJ5uofnFUiD0cRgFpCkALgMfxBWEzY9wuYc8U8LvVM6qz9gh23B1cMH2wxhKqvBHBgBNUU9rsaBwvMuTMLlTrPHXe45rrC//KHFHDnUh/2bUiASeXId9mkQSS2imsyOz61pn4Pa3Y/Ir/Lp3kNdtiV80knKOYrfxBn2yqdf3i1s47o1TEuMBRKRDaBrTc9qmROkH1aDhrqtaRmOWtF0+49xEmfEQjMlDdrBX7IAr+Z4jXI/cZaK1+o7R6coqCXuV68ESx90ahe9y1FniOcGxeRH/z2RQaXkc+g34hRwEMmAaep0O76r0CKgdtpEDJ9gpJSAXIoXnMtgzDFHMx0EUkTEoieK2URGD+T94Gnshs=
